# Required to run your project under the correct environment.
language: php

services:
  - mysql

# Versions of PHP you want your project run with.
php:
  - 5.6
  - 7.0
  
sudo: false

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - COMPOSER_DISCARD_CHANGES=1 composer install --dev --prefer-source --no-interaction

# Commands to be run before your environment runs.
before_script:
  - mysql -e 'create database laravel_like_comment;'
  - php artisan vendor:publish
  
script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
